---
- block:
  - name: "CrowdStrike Falcon | Validate Required API URL Is Defined"
    fail:
      msg: "falcon_api_url is not configured! Please configure falcon_api_url and re-run the installation again!"
    when: not falcon_api_url
 
  - name: CrowdStrike Falcon | Validate CrowdStrike API Client ID Is Defined
    fail:
      msg: falcon_api_client_id is not configured! Please configure falcon_api_client_id and re-run the installation again!
    when: not falcon_api_client_id

  - name: CrowdStrike Falcon | Validate CrowdStrike API Client Secret Is Defined
    fail:
      msg: falcon_api_client_secret is not configured! Please configure falcon_api_client_secret and re-run the installation again!
    when: not falcon_api_client_secret

  when: falcon_install_method == "api"

- name: CrowdStrike Falcon | Configure Python Interpreter for older Linux OSes
  set_fact:
    ansible_python_interpreter: /usr/bin/python
  when: ansible_distribution == "Amazon"

- name: CrowdStrike Falcon | Determine if Endpoint Operating System Is RHEL, CentOS, or Oracle Linux
  set_fact:
     falcon_target_os: RHEL/CentOS/Oracle
     falcon_os_family: "{{ ansible_system | lower }}"
  when: ansible_os_family == "RedHat"

- name: CrowdStrike Falcon | Determine if Target OS Is Amazon Linux
  set_fact:
    falcon_target_os: "Amazon%20Linux"
    falcon_os_family: "{{ ansible_system | lower }}"
  when: ansible_distribution == "Amazon"

- name: "CrowdStrike Falcon | Endpoint Operating System Detected Is {{ ansible_distribution }}"
  set_fact:
     falcon_target_os: "{{ ansible_distribution }}"
     falcon_os_family: "{{ ansible_system | lower }}"
  when: ansible_distribution in ["Ubuntu", "Debian", "SLES"]

- set_fact:
    installed_sensor: falcon-sensor
  when:
    - ansible_pkg_mgr in linux_packagers

- set_fact:
    non_win_pkg: "{{ installed_sensor }}"
  when:
    - ansible_pkg_mgr in linux_packagers
    - falcon_sensor_download is not defined

- name: CrowdStrike Falcon | Verify Temporary Install Directory Exists
  file:
    path: "{{ falcon_install_tmp_dir }}"
    state: directory
  when: falcon_install_tmp_dir is defined
